# Generated by Django 5.0.2 on 2025-04-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("litrevu", "0002_userblocks_userblocks_cannot_block_self_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_photo",
        ),
    ]
